export const states: Array<{ value: string; label: string }> = [
  { value: "1", label: "Aguascalientes" },
  { value: "2", label: "Campeche" },
  { value: "3", label: "Chiapas" },
  { value: "4", label: "Chihuahua" },
  { value: "5", label: "Coahuila" },
  { value: "6", label: "Colima" },
  { value: "7", label: "Durango" },
  { value: "8", label: "Estado de México" },
  { value: "9", label: "Guanajuato" },
  { value: "10", label: "Guerrero" },
  { value: "11", label: "Hidalgo" },
  { value: "12", label: "Jalisco" },
  { value: "13", label: "Michoacán" },
  { value: "14", label: "Morelos" },
  { value: "15", label: "Nayarit" },
  { value: "16", label: "Nuevo León" },
  { value: "17", label: "Oaxaca" },
  { value: "18", label: "Puebla" },
  { value: "19", label: "Querétaro" },
  { value: "20", label: "Quintana Roo" },
  { value: "21", label: "San Luis Potosí" },
  { value: "22", label: "Sinaloa" },
  { value: "23", label: "Sonora" },
  { value: "24", label: "Tabasco" },
  { value: "25", label: "Tamaulipas" },
  { value: "26", label: "Tlaxcala" },
  { value: "27", label: "Veracruz" },
  { value: "28", label: "Yucatán" },
  { value: "29", label: "Zacatecas" },
  { value: "30", label: "Baja California" },
  { value: "31", label: "Baja California Sur" },
  { value: "32", label: "Ciudad de México" },
];
